### PR TITLE
SW views can be created even if time column alias isn't arrival_timestamp

### PR DESCRIPTION
**Pull request by usmanm**
Also, since we allow SWs to be defined on columns other than `arrival_timestamp`, maybe we should use an alias like `sw_column` to refer to the time column in the SW clause rather than `arrival_timestamp` when referring to it in `CREATE VIEW`.

### CODE REVIEW

**Comment by derekjn** [comment]
Looks good!

**Comment by usmanm** [comment]
Should we use the alias sw_timestamp instead of arrival_timestamp to refer to the column?

**Comment by derekjn** [comment]
I don't know of any of our users who are using sliding windows without `arrival_timestamp`, so I think that changing the alias `sw_timestamp` may be confusing to users. The correct way to handle this is probably to actually detect the name of the underlying sliding window column and allow that to be pushed down. That may require a bit of work and probably isn't worth spending time on just yet.

**Comment by usmanm** [comment]
I think it shouldn't be too tricky to go. Lemme see if I can crank it out in an hour.

**Pull request closed without merging**
