### PR TITLE
Allow the dockerfile entrypoint to be reused by child images

### PR DESCRIPTION
**Pull request by joaosa**
Here's the associated issue: https://github.com/pipelinedb/pipelinedb/issues/1941

### CODE REVIEW

**Comment by derekjn** [comment]
@joaosa thank you so much! For reference purposes, do you mind briefly explaining what the issue is and why exactly this resolves it? Much appreciated! :pray:

**Comment by joaosa** [comment]
You're welcome!

The main idea is to allow one to run any script before booting pipelinedb, while reusing pipelinedb's entrypoint and, thus, not having to boot it explicitly.

Here's an example:

dockerfile
```
FROM pipelinedb/pipelinedb:latest
ADD start.sh /
CMD ["/bin/sh", "/start.sh"]
```

start.sh
```
# do whatever you need to do
# e.g. fix permissions on a volume

# boot pipelinedb through its entrypoint
/entrypoint.sh pipelinedb
```

**Comment by joaosa** [comment]
Turns out this is currently possible by calling `/usr/local/bin/docker-entrypoint.sh pipelinedb` instead.

It turns out `pipelinedb/pipelinedb:latest` isn't up to date and it seems to be a much older version. I'd say it's `0.9.6` (https://hub.docker.com/r/pipelinedb/pipelinedb/tags/).

**Comment by joaosa** [comment]
Closing this as it's no longer relevant to me

**Pull request closed without merging**
