### PR TITLE
override libpq default port

### PR DESCRIPTION
**Pull request by ker2x**
see #1057

### CODE REVIEW

**Comment by derekjn** [comment]
Thanks @ker2x ! Do you mind signing our CLA so we can accept any pull requests you send our way?

**Comment by ker2x** [comment]
sure, no problem. i'll see that tomorrow :)

**Comment by ker2x** [comment]
doh!?

**Comment by ker2x** [comment]
i can see how my patch break stuff.

It act as we passed -p option so it also override environment var and psql rc file.

This patch sux, sorry :)

**Pull request closed without merging**
