### PR TITLE
Multiplicative back off for queries that throw errors 

### PR DESCRIPTION
**Pull request by usmanm**
Still trying to figure out how to best test this, ideas?

### CODE REVIEW

**Comment by derekjn** [comment]
Don't we want this to also work if the process crashes even before entering the loop? If that happens the proc will enter a recovery loop that can potentially peg the CPU.

**Comment by usmanm** [comment]
That control will probably have to go into the scheduler, because outside of this the process will crash with the postmaster will restart it.

**Comment by derekjn** [comment]
We should just make the scheduler stop trying to restart a proc that crashes repeatedly. Is that outside the scope of this diff?

**Comment by usmanm** [comment]
Yea, that'll require tweaking the background worker infrastructure, which I have been meaning to for a bit. Will create an issue for it.

**Comment by derekjn** [comment]
Regarding testing, you could write a pytest that does something evil like deletes the matrel's files under the data directory which will surely cause the combiner to explode. Then you can probably look at the combiner stats and verify that the number of errors is reasonable (shouldn't be ridiculously high).

**Comment by usmanm** [comment]
Going to create PLpgSQL aggregates that throw errors on some predefined inputs, and then supply those inputs and see how data is lost.

**Comment by usmanm** [comment]
This is good to go now.

**Comment by usmanm** [comment]
This is still unstable, so going to remove it from `0.8.0`.

**Comment by usmanm** [comment]
Will re-open when ready.

**Pull request closed without merging**
