### PR TITLE
1575 zmq

### PR DESCRIPTION
**Pull request by usmanm**

### CODE REVIEW

**Comment by derekjn** [comment]
Dude this is awesome, such a huge improvement! Most of the basics seem to be covered, I'll report back here with some corner cases I'm starting to test.

**Comment by derekjn** [comment]
```
create continuous view v as select x::integer, bloom_agg(x::integer) FROM stream group by x;
insert into stream (k, x) select x AS k, x from generate_series(1, 8) as x; 

STATEMENT:  insert into test_bloom_stream (k, x) select x AS k, x from generate_series(1, 8) as x;
TRAP: FailedAssertion("!(len <= continuous_query_batch_size)", File: "pzmq.c", Line: 247, PID: 2318, Query: v)
Assertion failure (PID 2318)
version: PipelineDB  at revision  on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2, 64-bit
backtrace:
pipelinedb: bgworker: worker0 [derek]   (ExceptionalCondition+0xb4)[0x98e27a]
pipelinedb: bgworker: worker0 [derek]   (pzmq_send+0x3c)[0x7788eb]
pipelinedb: bgworker: worker0 [derek]   (microbatch_send+0x50)[0x777cb0]
pipelinedb: bgworker: worker0 [derek]   [0x7795de]
pipelinedb: bgworker: worker0 [derek]   (CombinerDestReceiverFlush+0x170)[0x77975c]
pipelinedb: bgworker: worker0 [derek]   [0x78d7c6]
pipelinedb: bgworker: worker0 [derek]   (ContinuousQueryWorkerMain+0x277)[0x78da80]
pipelinedb: bgworker: worker0 [derek]   [0x78c2da]
pipelinedb: bgworker: worker0 [derek]   (StartBackgroundWorker+0x2ac)[0x79d469]
pipelinedb: bgworker: worker0 [derek]   [0x7b1a42]
pipelinedb: bgworker: worker0 [derek]   [0x7b1d1c]
pipelinedb: bgworker: worker0 [derek]   [0x7ac8bb]
pipelinedb: bgworker: worker0 [derek]   (PostmasterMain+0x10ee)[0x7abc9d]
```

**Comment by derekjn** [comment]
With sync inserts disabled, it seems like something isn't being flushed somewhere:

```
create continuous view v as select count(*) from stream;
create continuous transform xform as select 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'::text
::text from input then execute procedure pipeline_stream_insert('stream');
insert into stream (x) values (0);
select * from v;
 count 
-------
(0 rows)
```

Even after seconds or minutes, the CV is still empty. The expected result shows up after stopping/starting the server, and works fine when sync inserts are enabled.

**Comment by usmanm** [comment]
```
test_output_streams.py::test_output_tree PASSED
test_output_streams.py::test_concurrent_sw_ticking PASSED
test_output_streams.py::test_transforms FAILEDHINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.

test_output_streams.py::test_transforms ERROR
```

`test_transform` hangs, I killed the insert proc. It hung waiting synchronous commits to complete.

**Comment by usmanm** [comment]
```
test_sanity.py <- base.py::test_concurrent_copy PASSED
test_sanity.py <- base.py::test_concurrent_inserts FAILED
```

Sleeping for a while before `conn.close()` doesn't help...

**Comment by usmanm** [comment]
```
LOG:  database system was shut down at 2016-08-02 16:49:02 PDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  continuous query scheduler started
LOG:  starting continuous query processes for database: "pipeline"
LOG:  continuous query process "worker0 [pipeline]" running with pid 17990
LOG:  continuous query process "worker1 [pipeline]" running with pid 17991
LOG:  continuous query process "combiner0 [pipeline]" running with pid 17992
LOG:  continuous query process "combiner1 [pipeline]" running with pid 17993
LOG:  backend pid is 18005 (from 127.0.0.1:40150)
PASSED
test_output_streams.py::test_concurrent_sw_ticking PASSED
test_output_streams.py::test_transforms Segmentation fault (PID 17992)
version: PipelineDB  at revision  on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609, 64-bit
backtrace:
pipelinedb: bgworker: combiner0 [pipeline]   (debug_segfault+0x34)[0x725c85]
/lib/x86_64-linux-gnu/libc.so.6(+0x354a0)[0x7f90a4d5e4a0]
pipelinedb: bgworker: combiner0 [pipeline]   [0x7a0ba8]
pipelinedb: bgworker: combiner0 [pipeline]   (ContinuousQueryCombinerMain+0x346)[0x7a1d60]
pipelinedb: bgworker: combiner0 [pipeline]   [0x79b732]
pipelinedb: bgworker: combiner0 [pipeline]   (StartBackgroundWorker+0x2ac)[0x7ad4c6]
pipelinedb: bgworker: combiner0 [pipeline]   [0x7c23bc]
pipelinedb: bgworker: combiner0 [pipeline]   [0x7c26a5]
pipelinedb: bgworker: combiner0 [pipeline]   [0x7c16d5]
/lib/x86_64-linux-gnu/libc.so.6(+0x354a0)[0x7f90a4d5e4a0]
/lib/x86_64-linux-gnu/libc.so.6(__select+0x13)[0x7f90a4e25cf3]
pipelinedb: bgworker: combiner0 [pipeline]   [0x7bcdd4]
pipelinedb: bgworker: combiner0 [pipeline]   (PostmasterMain+0x1114)[0x7bc4c7]
pipelinedb: bgworker: combiner0 [pipeline]   [0x6e90fb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f90a4d49830]
pipelinedb: bgworker: combiner0 [pipeline]   (_start+0x29)[0x469ce9]
```

The state for a query ID in `all_queries` bitmap is not `NULL` but has been freed...

**Pull request closed without merging**
